### ISSUE TITLE
What version of LWJGL is this?

### ISSUE THREAD

**Issue by catfoolyou** [PeytonPlayz595/LWJGL-TeaVM#1]

**Comment by radmanplays** [comment]
i think lwjgl 2.9.1

**Comment by PeytonPlayz595** [comment]
@catfoolyou This project is based off of LWJGL 2.9.3

**Comment by PeytonPlayz595** [comment]
I wouldn't recommend using it for anything atm since there is quite a few missing features and bugs but I did manage to port a few classic versions using this, and I reported 0.30 with it

**Comment by catfoolyou** [comment]
Ah. I'm using LWJGL3 for 1.12, but this might come in handy eventually. Thanks.
